FROM 545095154182.dkr.ecr.us-east-1.amazonaws.com/corretto-clojure:jdk-8-lein

WORKDIR /app
ADD project.clj /app/project.clj
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
RUN lein deps

ADD . /app
CMD exec lein trampoline test
