(ns storefront.events)

(def navigate [:navigation])
(def navigate-home (conj navigate :home))
(def navigate-category (conj navigate :category))
(def navigate-guarantee (conj navigate :guarantee))
(def navigate-help (conj navigate :help))
(def navigate-privacy (conj navigate :privacy))
(def navigate-tos (conj navigate :tos))
(def navigate-sign-in (conj navigate :sign-in))
(def navigate-sign-up (conj navigate :sign-up))

(def control [:control])
(def control-menu (conj control :menu))
(def control-menu-expand (conj control-menu :expand))
(def control-menu-collapse (conj control-menu :collapse))
(def control-sign-in (conj control :sign-in))
(def control-sign-in-change (conj control-sign-in :change))
(def control-sign-in-submit (conj control-sign-in :submit))
(def control-sign-out (conj control :sign-out))
(def control-sign-up (conj control :sign-up))
(def control-sign-up-change (conj control-sign-up :change))
(def control-sign-up-submit (conj control-sign-up :submit))

(def api [:api])
(def api-success (conj api :success))

(def api-success-taxons (conj api-success :taxons))
(def api-success-store (conj api-success :store))
(def api-success-category (conj api-success :category))
(def api-success-products (conj api-success :products))
(def api-success-sign-in (conj api-success :sign-in))
(def api-success-sign-up (conj api-success :sign-up))
