var Swipe = {}
Swipe.setup = function() {}
Swipe.slide = function(to, speed) {}
Swipe.prev = function() {}
Swipe.next = function() {}
Swipe.restart = function() {}
Swipe.stop = function() {}
Swipe.getPos = function() {}
Swipe.getNumSlides = function() {}
Swipe.kill = function() {}
